---
title: "Data Analysis 2 Tutorial week 6"
author: "Helen McDermott"
date: "2/16/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("TDAmapper")
```

```{r}
library(locfit)
library(TDAmapper)
library(igraph)
data(chemdiab)
summary(chemdiab)
```

```{r}
normdiab <- chemdiab
normdiab[,1:5] <- scale(normdiab[,1:5],center=FALSE)
normdiab.dist <- dist(normdiab[,1:5])
normdiab.dist
```

```{r}
eccentricities<-read.csv("data/ecc1.csv")
```

```{r}
#diab.mapper <- mapper1D(
#           dist_object = normdiab,
#           filter_values = eccentricities,
#           num_intervals = 4,
#           percent_overlap = 50,
#           num_bins_when_clustering = 20)
#diab.graph <- graph.adjacency(diab.mapper$adjacency, mode="undirected")
#plot(diab.graph )
```


```{r}
data1<-read.csv('data/data1.csv',header=FALSE)
eccentricities<-read.csv("data/ecc1.csv", header = FALSE)
Data1.mapper<-mapper1D(distance_matrix=data1,
                       filter_values=eccentricities,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data1.graph<-graph.adjacency(Data1.mapper$adjacency,mode="undirected")
plot(Data1.graph,layout=layout.auto(Data1.graph))
```

```{r}
 data2<-read.csv('data/data2.csv',header=FALSE)
eccentricities2<-read.csv("data/ecc2.csv", header = FALSE)
Data2.mapper<-mapper1D(distance_matrix=data2,
                       filter_values=eccentricities2,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data2.graph<-graph.adjacency(Data2.mapper$adjacency,mode="undirected")
plot(Data2.graph,layout=layout.auto(Data2.graph))
```


```{r}
data3<-read.csv('data/data3.csv',header=FALSE)
eccentricities3<-read.csv("data/ecc3.csv", header = FALSE)
Data3.mapper<-mapper1D(distance_matrix=data3,
                       filter_values=eccentricities3,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data3.graph<-graph.adjacency(Data3.mapper$adjacency,mode="undirected")
plot(Data3.graph,layout=layout.auto(Data3.graph))
```
```{r}
data4<-read.csv('data/data4.csv',header=FALSE)
eccentricities4<-read.csv("data/ecc4.csv", header = FALSE)
Data4.mapper<-mapper1D(distance_matrix=data4,
                       filter_values=eccentricities4,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data4.graph<-graph.adjacency(Data4.mapper$adjacency,mode="undirected")
plot(Data4.graph,layout=layout.auto(Data4.graph))
```

```{r}
data5<-read.csv('data/data5.csv',header=FALSE)
eccentricities5<-read.csv("data/ecc5.csv", header = FALSE)
Data5.mapper<-mapper1D(distance_matrix=data5,
                       filter_values=eccentricities5,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data5.graph<-graph.adjacency(Data5.mapper$adjacency,mode="undirected")
plot(Data5.graph,layout=layout.auto(Data5.graph))
```

```{r}
data6<-read.csv('data/data6.csv',header=FALSE)
eccentricities6<-read.csv("data/ecc6.csv", header = FALSE)
Data6.mapper<-mapper1D(distance_matrix=data6,
                       filter_values=eccentricities6,
                       num_intervals=15,  # 15
                       percent_overlap=73,
                       num_bins_when_clustering = 15)

Data6.graph<-graph.adjacency(Data6.mapper$adjacency,mode="undirected")
plot(Data6.graph,layout=layout.auto(Data6.graph))
```

